site_name: AutoHotkey v2 – Extended API
nav:
  - Home: index.md
  - API: API.md
theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
markdown_extensions:
  - admonition
  - codehilite
  - tables
  - toc:
      permalink: true

